### PR TITLE
Fix missing `environment` prop in Custom window section

### PR DESCRIPTION
**Pull request by hazem3500**

### CODE REVIEW

**Comment by silviuaavram** [comment]
Awesome, thanks @hazem3500 ! I think the codesandbox example is also broken, can you create a PR there as well please? Should be similar to this one.

**Comment by silviuaavram** [comment]
https://github.com/downshift-js/downshift-examples/blob/master/src/hooks/useCombobox/iframe.js here I mean

**Comment by hazem3500** [comment]
@silviuaavram made the PR [here](https://github.com/downshift-js/downshift-examples/pull/33)

**Comment by silviuaavram** [comment]
Great! Thanks very much!

**Pull request merged**
